# Generated by Django 4.1.7 on 2023-04-03 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uploadedfile',
            table='Files',
        ),
    ]
