# Generated by Django 4.1.7 on 2023-04-11 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='accessId',
        ),
        migrations.CreateModel(
            name='FileUserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessId', models.CharField(default='a', max_length=255)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.file')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'FileUserAccess',
            },
        ),
        migrations.AddField(
            model_name='file',
            name='users',
            field=models.ManyToManyField(through='api.FileUserAccess', to='api.user'),
        ),
    ]
