# Generated by Django 4.1.7 on 2023-04-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_file_accessid_fileuseraccess_file_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='users',
        ),
        migrations.AddField(
            model_name='file',
            name='accessId',
            field=models.CharField(default='a', max_length=255),
        ),
        migrations.DeleteModel(
            name='FileUserAccess',
        ),
    ]
