# Generated by Django 4.1.7 on 2023-04-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=255)),
                ('accessId', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Files',
            },
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
