# Generated by Django 4.1.7 on 2023-04-04 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_file_delete_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='accessId',
        ),
    ]
