# Generated by Django 4.1.7 on 2023-04-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_file_accessid'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='accessId',
            field=models.CharField(default='a', max_length=255),
        ),
    ]
